spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never
zenvia:
  from: sassy-nannyberry
  token: svbfnSax7RN2KYB8Fz5zR9tqunWtuun8XgNb
  url: https://api.zenvia.com/v2/channels/whatsapp/messages
  fileUrl: https://api.zenvia.com/v2/files
